#!/usr/bin/env ruby
require "bundler/setup"
require "senju"
require "ap"
require "colorize"

def link_to(text, url)
  "\e]8;;#{url}\e\\#{text}\e]8;;\e\\"
end

def print_issue(issue)
  print link_to("##{issue.no} ".colorize(:blue).bold, issue.url) + issue.title + "\n"
end

def exec(repo, command)
  case command
  when "issues"
    repo.issues.each do |issue|
      print_issue(issue)
    end
  when "pr"
    repo.pull_requests.each do |issue|
      print_issue(issue)
    end
  end
end

repo = ARGV[0]
command = ARGV[1] || "issues"

if repo
  exec(Senju::Repository.find(repo), command)
else
  Senju::Repository.all.each do |repo|
    puts "================= #{repo.name} ====================".colorize(:green).bold
    exec(repo, command)
  end
end
